# Generated by Django 3.2.3 on 2022-02-15 11:49

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20220215_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='First Name')),
                ('species', models.TextField(max_length=100, verbose_name='Last Name')),
                ('weight', models.TextField(max_length=100, verbose_name='Last Name')),
                ('length', models.TextField(max_length=100, verbose_name='Last Name')),
                ('latitude', models.TextField(max_length=100, verbose_name='Last Name')),
                ('longitude', models.TextField(max_length=100, verbose_name='Last Name')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('photo', versatileimagefield.fields.VersatileImageField(upload_to='photo/', verbose_name='photo')),
                ('photo_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
            ],
            options={
                'verbose_name': 'Alldata',
                'verbose_name_plural': 'Alldata',
            },
        ),
        migrations.DeleteModel(
            name='Photodata',
        ),
    ]
