# Generated by Django 3.2.3 on 2022-02-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20220215_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='latitude',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='longitude',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
