# Generated by Django 3.2.3 on 2022-02-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_auto_20220215_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='species',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
    ]
