# Generated by Django 3.2.3 on 2022-02-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_alter_alldata_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='species',
            field=models.CharField(max_length=100),
        ),
    ]
